version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

  # Maintain dependencies for terraform
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
