name: Production backoffice

on: workflow_dispatch

jobs:
  pre_deployment_checks:
    name: Pre-deployment checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
      - name: Run formatter
        run: npm run format:check
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build

  deploy:
    name: Deploy Production Environment
    runs-on: ubuntu-latest
    needs: [pre_deployment_checks]
    if: github.ref == 'refs/heads/main'
    environment: production
    env:
      TF_WORKSPACE: production
      REACT_APP_AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
      REACT_APP_AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
      REACT_APP_API_URL: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hashicorp/setup-terraform@v1.3.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Build
        run: npm ci && npm run build
      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
      - name: Create resources
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=production.tfvars
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://mca-beacons-backoffice-production --delete
