name: CI/CD pipeline - development backoffice

on: push

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm install -g create-react-app && npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Debug
        run: git status

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run tests
        run: npm run test

  cypress_tests:
    name: Cypress tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          build: npm run build
          wait-on: "http://localhost:3000"

  prettier_check:
    name: Prettier check
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run prettier
        run: npm run format:check

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Restore cache
        uses: actions/cache@v2.1.4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run linter
        run: npm run lint

  deploy:
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    needs:
      [
        install_dependencies,
        unit_tests,
        cypress_tests,
        lint_check,
        prettier_check,
      ]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Build React App
        run: npm install && npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://beacons-backoffice-dev --delete
