name: Staging backoffice

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy Staging Environment
    runs-on: ubuntu-latest
    needs: [unit_tests, prettier_check, lint_check, build]
    if: github.ref == 'refs/heads/main'
    environment: staging
    env:
      TF_WORKSPACE: staging
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hashicorp/setup-terraform@v1.3.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.11
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
      - name: Create resources
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=staging.tfvars
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./public/ s3://mca-beacons-backoffice-staging --delete
