name: Development backoffice

on: push

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  cypress_tests:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          build: npm run build
          wait-on: "http://localhost:3000"

  prettier_check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
      - name: Run prettier
        run: npm run format:check

  lint_check:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  deploy:
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    needs: [unit_tests, cypress_tests, lint_check, prettier_check]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/f/https'
    env:
      TF_WORKSPACE: dev
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Build
        run: npm ci && npm run build
      - name: terraform init
        working-directory: terraform
        run: terraform init
      - name: terraform apply
        id: tf-apply
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=config.tfvars
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://mca-beacons-backoffice-dev --delete
