name: Development backoffice

on: [push, workflow_dispatch]

jobs:
  deploy:
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: development
    env:
      TF_WORKSPACE: dev
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: hashicorp/setup-terraform@v1.3.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.11
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Initialize terraform
        working-directory: terraform
        run: terraform init
      - name: Create resources
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=dev.tfvars
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./public/ s3://mca-beacons-backoffice-dev --delete
